import type { ClothingItem, Outfit, ProcessingJob } from "@/lib/types";

export const clothingItems: ClothingItem[] = [
  {
    id: "cream-ribbed-knit",
    name: "Cream ribbed knit",
    category: "tops",
    subcategory: "Long sleeve top",
    primaryColor: "Cream",
    season: ["Fall", "Winter", "Spring"],
    occasions: ["Everyday", "Dinner", "Work"],
    tags: ["Soft", "Fitted", "Neutral"],
    favorite: true,
    addedAt: "2026-08-19",
    visual: "knit",
    tone: "oat",
  },
  {
    id: "black-tailored-trouser",
    name: "Black tailored trouser",
    category: "bottoms",
    subcategory: "Trouser",
    primaryColor: "Black",
    season: ["All season"],
    occasions: ["Work", "Dinner", "Going out"],
    tags: ["Tailored", "Straight leg", "Basic"],
    favorite: true,
    addedAt: "2026-08-11",
    visual: "pants",
    tone: "charcoal",
  },
  {
    id: "washed-blue-jean",
    name: "Washed blue jean",
    category: "bottoms",
    subcategory: "Relaxed denim",
    primaryColor: "Denim blue",
    season: ["All season"],
    occasions: ["Casual", "Errands", "Weekend"],
    tags: ["Relaxed", "Denim", "Comfortable"],
    favorite: false,
    addedAt: "2026-07-28",
    visual: "pants",
    tone: "denim",
  },
  {
    id: "clay-silk-skirt",
    name: "Clay silk skirt",
    category: "bottoms",
    subcategory: "Midi skirt",
    primaryColor: "Clay",
    season: ["Spring", "Summer", "Fall"],
    occasions: ["Church", "Dinner", "Date night"],
    tags: ["Silk", "Midi", "Dressy casual"],
    favorite: true,
    addedAt: "2026-08-02",
    visual: "skirt",
    tone: "clay",
  },
  {
    id: "espresso-slip-dress",
    name: "Espresso slip dress",
    category: "dresses",
    subcategory: "Midi dress",
    primaryColor: "Espresso",
    season: ["Spring", "Summer", "Fall"],
    occasions: ["Dinner", "Wedding", "Going out"],
    tags: ["Minimal", "Midi", "Statement"],
    favorite: true,
    addedAt: "2026-06-17",
    visual: "dress",
    tone: "espresso",
  },
  {
    id: "stone-linen-shirt",
    name: "Stone linen shirt",
    category: "tops",
    subcategory: "Button-up shirt",
    primaryColor: "Stone",
    season: ["Spring", "Summer"],
    occasions: ["Travel", "Casual", "Beach"],
    tags: ["Linen", "Relaxed", "Layering"],
    favorite: false,
    addedAt: "2026-08-20",
    visual: "tee",
    tone: "stone",
  },
  {
    id: "black-cropped-jacket",
    name: "Black cropped jacket",
    category: "outerwear",
    subcategory: "Light jacket",
    primaryColor: "Black",
    season: ["Spring", "Fall"],
    occasions: ["Going out", "Dinner", "Concert"],
    tags: ["Cropped", "Structured", "Layering"],
    favorite: false,
    addedAt: "2026-05-09",
    visual: "jacket",
    tone: "ink",
  },
  {
    id: "cognac-ankle-boot",
    name: "Cognac ankle boot",
    category: "shoes",
    subcategory: "Ankle boot",
    primaryColor: "Cognac",
    season: ["Fall", "Winter", "Spring"],
    occasions: ["Dinner", "Work", "Going out"],
    tags: ["Leather", "Heeled", "Warm"],
    favorite: true,
    addedAt: "2026-03-12",
    visual: "shoe",
    tone: "cognac",
  },
  {
    id: "ivory-sneaker",
    name: "Ivory leather sneaker",
    category: "shoes",
    subcategory: "Low-top sneaker",
    primaryColor: "Ivory",
    season: ["All season"],
    occasions: ["Casual", "Errands", "Travel"],
    tags: ["Leather", "Comfortable", "Everyday"],
    favorite: false,
    addedAt: "2026-07-14",
    visual: "shoe",
    tone: "ivory",
  },
  {
    id: "black-shoulder-bag",
    name: "Black shoulder bag",
    category: "bags",
    subcategory: "Shoulder bag",
    primaryColor: "Black",
    season: ["All season"],
    occasions: ["Everyday", "Dinner", "Going out"],
    tags: ["Leather", "Minimal", "Quick outfit"],
    favorite: true,
    addedAt: "2026-04-22",
    visual: "bag",
    tone: "black",
  },
  {
    id: "sage-lounge-knit",
    name: "Sage lounge knit",
    category: "loungewear",
    subcategory: "Soft pullover",
    primaryColor: "Sage",
    season: ["Fall", "Winter"],
    occasions: ["Housewear", "Lounge", "Travel"],
    tags: ["Soft", "Oversized", "Comfortable"],
    favorite: false,
    addedAt: "2026-01-16",
    visual: "knit",
    tone: "sage",
  },
  {
    id: "white-fitted-tee",
    name: "White fitted tee",
    category: "tops",
    subcategory: "T-shirt",
    primaryColor: "White",
    season: ["All season"],
    occasions: ["Everyday", "Casual", "Layering"],
    tags: ["Fitted", "Basic", "Cotton"],
    favorite: false,
    addedAt: "2025-12-02",
    visual: "tee",
    tone: "white",
  },
];

export const outfits: Outfit[] = [
  {
    id: "soft-neutral-dinner",
    name: "Soft neutral dinner",
    occasion: "Dinner",
    itemIds: ["cream-ribbed-knit", "black-tailored-trouser", "cognac-ankle-boot"],
    favorite: true,
    createdAt: "2026-08-21",
  },
  {
    id: "easy-sunday",
    name: "Easy Sunday",
    occasion: "Church",
    itemIds: ["stone-linen-shirt", "clay-silk-skirt", "ivory-sneaker"],
    favorite: false,
    createdAt: "2026-08-16",
  },
  {
    id: "late-dinner",
    name: "Late dinner",
    occasion: "Going out",
    itemIds: ["espresso-slip-dress", "black-cropped-jacket", "black-shoulder-bag"],
    favorite: true,
    createdAt: "2026-07-30",
  },
];

export const processingJobs: ProcessingJob[] = [
  {
    id: "job-1",
    label: "Cream linen trousers",
    status: "processing",
    detail: "Reading color, material, and tags",
  },
  {
    id: "job-2",
    label: "Striped weekend shirt",
    status: "needs_review",
    detail: "Choose between top and outerwear",
  },
];

export function getClothingItem(id: string) {
  return clothingItems.find((item) => item.id === id);
}

export function getOutfitItems(outfit: Outfit) {
  return outfit.itemIds
    .map((id) => getClothingItem(id))
    .filter((item): item is ClothingItem => Boolean(item));
}
